#!/bin/bash

launchCcm() {
	export CLUSTER_NAME=$1
	export CCM_AUTH_TOKEN='f2e546ce91fcf3546aa989de02cdc6c64d276bb9'

	./build/start_ccm_cluster.sh
}

cosmosAuth() {
	http --ignore-stdin --verify no "https://${1}/acs/api/v1/auth/login" uid=bootstrapuser password=deleteme | jq -r ".token"
}

authSbt() {
	export COSMOS_AUTHORIZATION_HEADER="token=$(http --ignore-stdin --verify no "https://${1}/acs/api/v1/auth/login" uid=bootstrapuser password=deleteme | jq -r ".token")"
	sbt -Dcom.mesosphere.cosmos.dcosUri="http://${1}"
}

itTest() {
	export COSMOS_AUTHORIZATION_HEADER="token=$(http --ignore-stdin --verify no "https://${1}/acs/api/v1/auth/login" uid=bootstrapuser password=deleteme | jq -r ".token")"
	sbt -Dcom.mesosphere.cosmos.dcosUri="http://${1}" "it:test"
}

psRepo() {
	http GET http://localhost:7070/service/ps/repository \
		Accept:'application/vnd.dcos.universe.repo+json;charset=utf-8;version=v3'
}

psPublish() {
	http POST http://localhost:7070/service/ps/package/publish \
		Accept:'application/vnd.dcos.package.publish-response+json;charset=utf-8;version=v1' \
		Content-Type:'application/vnd.dcos.package.publish-request+json;charset=utf-8;version=v1' \
		packageBundle:=@$1
}

psRun() {
	java -jar package-store/target/scala-2.11/package-store_2.11-0.2.0-SNAPSHOT-one-jar.jar
}

cosmosRun() {
	mkdir /tmp/cosmos
	java -jar cosmos-server/target/scala-2.11/cosmos-server_2.11-${1}-SNAPSHOT-one-jar.jar \
		     -com.mesosphere.cosmos.dcosUri=${2}
}

cosmosRepo() {
	http GET http://localhost:7070/service/ps/repository \
		Accept:'application/vnd.dcos.universe.repo+json;charset=utf-8;version=v3'
}

cosmosPublish() {
	http POST http://localhost:7070/package/publish \
		Accept:'application/vnd.dcos.package.publish-response+json;charset=utf-8;version=v1' \
		Content-Type:'application/vnd.dcos.package.publish-request+json;charset=utf-8;version=v1' \
		packageBundle:=@$1
}

cosmosRepoAdd() {
	http POST http://localhost:7070/package/repository/add \
		Accept:'application/vnd.dcos.package.repository.add-response+json;charset=utf-8;version=v1' \
		Content-Type:'application/vnd.dcos.package.repository.add-request+json;charset=utf-8;version=v1' \
		name=$1 uri=$2
}

cosmosRepoList() {
	http POST http://localhost:7070/package/repository/list \
		Accept:'application/vnd.dcos.package.repository.list-response+json;charset=utf-8;version=v1' \
		Content-Type:'application/vnd.dcos.package.repository.list-request+json;charset=utf-8;version=v1' \
		body=''
}

cosmosSearch() {
	http POST http://localhost:7070/package/search \
		Accept:'application/vnd.dcos.package.search-response+json;charset=utf-8;version=v1' \
		Content-Type:'application/vnd.dcos.package.search-request+json;charset=utf-8;version=v1' \
		body=''
}
